// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobvNUqmXlPbYZLpig_02D63NbXDgWK9s',
    appId: '1:347602692095:web:dd62cec4744cb961b6e9ca',
    messagingSenderId: '347602692095',
    projectId: 'musicapp-139a6',
    authDomain: 'musicapp-139a6.firebaseapp.com',
    storageBucket: 'musicapp-139a6.appspot.com',
    measurementId: 'G-N5Z4LPMF0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTQafHFNQ-9AkU1_Ib_AYWLCz3YMKqag',
    appId: '1:347602692095:android:766c10a06f3f02e1b6e9ca',
    messagingSenderId: '347602692095',
    projectId: 'musicapp-139a6',
    storageBucket: 'musicapp-139a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1fLSxe95JkWsNz8mXxvRmAEnTTEn1Qs',
    appId: '1:347602692095:ios:b9cd1d9e5ff0ca73b6e9ca',
    messagingSenderId: '347602692095',
    projectId: 'musicapp-139a6',
    storageBucket: 'musicapp-139a6.appspot.com',
    iosBundleId: 'com.music.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF1fLSxe95JkWsNz8mXxvRmAEnTTEn1Qs',
    appId: '1:347602692095:ios:b9cd1d9e5ff0ca73b6e9ca',
    messagingSenderId: '347602692095',
    projectId: 'musicapp-139a6',
    storageBucket: 'musicapp-139a6.appspot.com',
    iosBundleId: 'com.music.musicApp',
  );
}
